print(type("Hello, World!"))
print(type(17))
print("Hello, World")
print(type(3.2))
print(type("17"))
print(type("3.2"))
print(type('This is a string.') )
print(type("And so is this.") )
print(type("""and this.""") )
print(type('''and even this...''') )

